[package]
name = "iced_winit"
version = "0.1.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = []
clipboard = ['window_clipboard']

[dependencies]
winit = "0.22"
# default-features includes x11-dl which we don't want on wayland
#winit = { git='https://github.com/Matthias-Fauconneau/winit', default-features=false }
#winit = { path='../../winit', default-features=false }
window_clipboard ={ version= "0.1", optional=true }
log = "0.4"

[dependencies.iced_native]
version = "0.2"
path = "../native"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
